export { demo } from "./demo";
export { showEnv } from "./1_environmens";
export { callbacks } from "./2_callbacks";
export { heros } from "../data/heros";
export { promises } from "./3_promises";
export { promiseRase } from "./4_promise_rase";
export { asyncComponent } from "./5_async";
export { asyncAwait } from "./6_async_await";
export { asyncAwaitExample } from "./7_aync_await_example";